Improve some of the error messages.

diff --git a/git-info b/git-info
--- a/git-info
+++ b/git-info
@@ -100,14 +100,15 @@ git_info () {
     local path="$1" dir relpath root git_dir
 
     if [ -d "$path" ]; then
-        dir="$(cd "$path" && pwd)" || die "$path: No such file or directory"
+        dir="$(cd "$path" && pwd)" || die "$path: Cannot cd to the directory"
         case "$path" in
             *.git)
                 git_dir="$dir"
                 ;;
         esac
     elif [ -f "$path" ]; then
-        dir="$(cd "$(dirname "$path")" && pwd)" || die "$path: No such file or directory"
+        dir="$(dirname "$path")"
+        dir="$(cd "$dir" && pwd)" || die "$dir: Cannot cd to the directory"
         relpath="$(basename "$path")"
     else
         die "$path: No such file or directory"
